#!/usr/bin/env python3
"""Generate human and flat control catalogs from control metadata."""

from __future__ import annotations

import argparse
import os
from collections import defaultdict
from pathlib import Path
from typing import Any

from control_metadata import REPOSITORY_ROOT, discover_controls, validate_controls


DOMAIN_CATALOG = (
    (
        "secure-design",
        "Secure Design",
        "脅威モデリング、trust boundary、abuse caseなど、実装前の設計判断。",
    ),
    (
        "secure-coding",
        "Secure Coding",
        "認証・認可、入力処理、secret、暗号など、application実装の安全性。",
    ),
    (
        "source-protection",
        "Source Protection",
        "開発端末、Git、repository、source access credential、公開露出の保護。",
    ),
    (
        "dependency-security",
        "Dependency Security",
        "registry、cooldown、install script、lockfile、artifact integrityの保護。",
    ),
    (
        "cicd-security",
        "CI/CD Security",
        "workflow dependency、command injection、権限、未信頼PR境界の保護。",
    ),
    (
        "build-security",
        "Build Security",
        "build隔離、hosted build、credential境界、provenance生成の保護。",
    ),
    (
        "container-cloud-iac-security",
        "Container / Cloud / IaC Security",
        "IaC Golden Path、container admission、runtime、cloud control planeの保護。",
    ),
    (
        "release-integrity",
        "Release Integrity",
        "署名、provenance、SBOM、supplier artifact、配布時の完全性。",
    ),
    (
        "ai-development-security",
        "AI Development Security",
        "AI coding agent、Skill、MCP、plugin、prompt、実行権限の保護。",
    ),
    (
        "detection-verification",
        "Detection / Verification",
        "脆弱性、secret、container、IaCなどを検出・検証する共通基盤。",
    ),
    (
        "governance-operations",
        "Governance / Operations",
        "例外、ownership、証跡、影響調査、継続運用とincident readiness。",
    ),
)

FRAMEWORK_LABELS = {
    "cisa-product-security-bad-practices": "CISA Product Security Bad Practices",
    "github-security-guidance": "GitHub Security Guidance",
    "mitre-attack": "MITRE ATT&CK",
    "mitre-atlas": "MITRE ATLAS",
    "nist-sp-800-190": "NIST SP 800-190",
    "nist-ssdf": "NIST SSDF",
    "openssf-osps-baseline": "OpenSSF OSPS Baseline",
    "owasp-agentic-top10": "OWASP Agentic Top 10",
    "owasp-aisvs": "OWASP AISVS",
    "owasp-asvs": "OWASP ASVS",
    "slsa": "SLSA",
}


def markdown_cell(value: object) -> str:
    return str(value).replace("\n", " ").replace("|", "\\|")


def control_readme_path(control: dict[str, Any], base: Path) -> str:
    readme = control["_directory"] / "README.md"
    return Path(os.path.relpath(readme, base)).as_posix()


def framework_links(control: dict[str, Any]) -> str:
    frameworks = {
        mapping["framework"]
        for mapping in control.get("mappings", [])
        if isinstance(mapping, dict) and isinstance(mapping.get("framework"), str)
    }
    if not frameworks:
        return "—"
    ordered = sorted(
        frameworks,
        key=lambda framework: (FRAMEWORK_LABELS.get(framework, framework), framework),
    )
    return " / ".join(
        f"[{FRAMEWORK_LABELS.get(framework, framework)}]"
        f"(../generated/mappings/{framework}.md)"
        for framework in ordered
    )


def render_flat_index(controls: list[dict[str, Any]]) -> str:
    lines = [
        "# Control Index",
        "",
        "Generated control catalog. Do not edit manually.",
        "",
        "| ID | Domain | Title | Checks | Status | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    output_directory = REPOSITORY_ROOT / "generated"
    for control in sorted(controls, key=lambda item: item["id"]):
        readme = control_readme_path(control, output_directory)
        control_link = f"[{control['id']}]({readme})"
        lines.append(
            "| "
            + " | ".join(
                markdown_cell(value)
                for value in (
                    control_link,
                    control["domain"],
                    control["title"],
                    len(control["checks"]),
                    control["status"],
                    control["evidence_level"],
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_control_catalog(controls: list[dict[str, Any]]) -> str:
    by_domain: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for control in controls:
        by_domain[control["domain"]].append(control)

    total_checks = sum(len(control["checks"]) for control in controls)
    lines = [
        "# Product Security Control Catalog",
        "",
        "<!-- Generated by scripts/generate-index.py. Do not edit manually. -->",
        "",
        "このページは、実装済みcontrolを目的別に探すための入口です。",
        "`control.yaml`を正本として`make generate-index`で生成されます。",
        "",
        f"現在、**{len(controls)} controls / {total_checks} atomic checks**を収録しています。",
        "",
        "## 使い方",
        "",
        "1. 下のドメイン一覧から、解決したいセキュリティ課題を選ぶ。",
        "2. control IDを開き、最初の「このcontrolを一枚で理解する」を確認する。",
        "3. `make verify-control CONTROL=<CONTROL-ID>`でfixture検証を実行する。",
        "4. 組織への導入時は、担当・確認方法・証跡・行単位mappingを"
        "[生成チェックリスト](../generated/checklists/product-security-checklist.md)で確認する。",
        "",
        "未実装control、依存関係、優先順位は"
        "[実装計画](../docs/PLANNED_CONTROLS.md)と"
        "[ロードマップ](../docs/ROADMAP.md)を参照してください。",
        "全controlをID順に見る場合は"
        "[フラット索引](../generated/CONTROL_INDEX.md)も利用できます。",
        "",
        "## ドメイン一覧",
        "",
        "| Domain | 主な対象 | Controls | Checks |",
        "|---|---|---:|---:|",
    ]
    for domain, label, description in DOMAIN_CATALOG:
        domain_controls = by_domain.get(domain, [])
        check_count = sum(len(control["checks"]) for control in domain_controls)
        lines.append(
            f"| [{label}](#domain-{domain}) | {description} | "
            f"{len(domain_controls)} | {check_count} |"
        )

    for domain, label, description in DOMAIN_CATALOG:
        domain_controls = sorted(
            by_domain.get(domain, []), key=lambda item: item["id"]
        )
        lines.extend(
            [
                "",
                f"<a id=\"domain-{domain}\"></a>",
                "",
                f"## {label}",
                "",
                description,
                "",
            ]
        )
        if not domain_controls:
            lines.extend(
                [
                    "実装済みcontrolはまだありません。候補は"
                    "[実装計画](../docs/PLANNED_CONTROLS.md)を参照してください。",
                ]
            )
            continue
        lines.extend(
            [
                "| Control | 達成する状態 | マッピング先 | Security functions | Checks | Maturity / Evidence |",
                "|---|---|---|---|---:|---|",
            ]
        )
        for control in domain_controls:
            readme = control_readme_path(control, REPOSITORY_ROOT / "controls")
            control_link = f"[{control['id']}]({readme})"
            functions = ", ".join(f"`{item}`" for item in control["security_functions"])
            maturity = f"`{control['status']}` / `{control['evidence_level']}`"
            lines.append(
                "| "
                + " | ".join(
                    (
                        control_link,
                        markdown_cell(control["summary"]),
                        framework_links(control),
                        functions,
                        str(len(control["checks"])),
                        maturity,
                    )
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "## 表示の意味",
            "",
            "- `マッピング先`: `control.yaml`に記録された標準、脅威分類、"
            "実装ガイダンス。各リンクからrequirement ID、relationship、confidence、"
            "対象checkを確認できます。mappingは準拠認定や完全なcoverageを意味しません。",
            "- `Security functions`: `prevent`、`detect`、`verify`、`respond`、"
            "`govern`のどの役割を持つか。",
            "- `Checks`: spreadsheetへ展開される原子的な確認行の数。",
            "- `Maturity`: `prototype`、`reference`、`adopted`などの成熟度。",
            "- `Evidence`: `E0`から`E4`の証跡レベル。`E3`は自動検証可能な"
            "reference implementationを意味し、組織への本番導入完了を意味しません。",
            "",
            "定義の詳細は"
            "[Control Model](../docs/CONTROL_MODEL.md)を参照してください。",
        ]
    )
    return "\n".join(lines) + "\n"


def expected_outputs(controls: list[dict[str, Any]]) -> dict[Path, str]:
    return {
        REPOSITORY_ROOT / "generated" / "CONTROL_INDEX.md": render_flat_index(
            controls
        ),
        REPOSITORY_ROOT / "controls" / "README.md": render_control_catalog(controls),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate human and flat control catalogs from control metadata."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when committed control catalogs are missing or stale.",
    )
    args = parser.parse_args()

    controls = discover_controls()
    errors = validate_controls(controls)
    if errors:
        for error in errors:
            print(f"ERROR {error}")
        return 1

    outputs = expected_outputs(controls)
    if args.check:
        stale = [
            path
            for path, expected in outputs.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            for path in stale:
                print(
                    f"ERROR stale generated control catalog: "
                    f"{path.relative_to(REPOSITORY_ROOT)}"
                )
            print("Run: make generate-index")
            return 1
        print(f"control catalogs are current: {len(controls)} controls")
        return 0

    for output, content in outputs.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        print(output.relative_to(REPOSITORY_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
